# Copyright (c) 2023-2025, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

site_author: WSO2

dev_addr: localhost:8000

# Configuration
theme:
  name: material
  font: false
  toc: false
  features:
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.instant.progress
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - search.suggest
    - search.share
  language: 'en'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: assets/libs/oxygen-ui-icons/1.7.3/crescent-bright-16.svg
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: assets/libs/oxygen-ui-icons/1.7.3/sun-16.svg
        name: Switch to light mode
  icon:
    logo: logo

# Breaks build if there's a warning
strict: false

validation:
  absolute_links: ignore

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - admonition
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs
  - attr_list

extra_css:
  - assets/libs/fontawesome-free-6.4.2-web/css/all.min.css
  - assets/css/theme.css

extra_javascript:
  - assets/js/theme.js

extra:
  material:
    jinja2content: true
  generator: false
  isolated_templates:
    - templates/complete-guide.html

  expanded_navs:
    - title: Guides
      options:
        - divider
        - verticle-line
    - title: Technology Guides
      options:
        - divider
    - title: Best Practice Guides

  # If the nav_override section is a child of expanded_nav. Add +1 to the level value
  nav_overrides:
    React:
      link: complete-guides/react/introduction
      level: 2
    Node.js:
      link: complete-guides/nodejs/introduction
      level: 2
    Angular:
      link: complete-guides/angular/introduction
      level: 2
    Vue:
      link: complete-guides/vue/introduction
      level: 2
    Node.js:
      link: complete-guides/nodejs/introduction
      level: 2
    .NET:
      link: complete-guides/dotnet/introduction
      level: 2
    Javascript:
      link: complete-guides/javascript/introduction
      level: 2
    Redirect-Based:
      link: complete-guides/nextjs/introduction
      level: 3
    App-Native:
      link: complete-guides/app-native/introduction
      level: 3
    Frontend Security:
      link: complete-guides/fesecurity/introduction
      level: 2

  nav_chip:
    Design login flow:
      type: ai
      level: 1

  nav_icons:
    Home:
      icon: octicons/home-16
      level: 1
    Get started:
      icon: octicons/rocket-16
      level: 1
    Connect Your App:
      icon: octicons/plug-16
      level: 1
    Design login flow:
      icon: octicons/paintbrush-16
      level: 1
    Guides:
      icon: octicons/book-16
      level: 1
    Tutorials:
      icon: octicons/mortar-board-16
      level: 1
    Setup:
      icon: octicons/gear-16
      level: 1
    SDKs:
      icon: octicons/package-16
      level: 1
    APIs:
      icon: octicons/code-16
      level: 1
    References:
      icon: octicons/link-external-16
      level: 1
    React:
      icon: fontawesome/brands/react
      level: 2
    .NET:
      icon: assets/libs/custom-icons/dotnet.svg
      level: 2
    Node.js:
      icon: fontawesome/brands/node-js
      level: 2
    Next.js:
      icon: assets/libs/custom-icons/nextjs.svg
      level: 2
    Angular:
      icon: fontawesome/brands/angular
      level: 2
    Vue:
      icon: fontawesome/brands/vuejs
      level: 2
    Javascript:
      icon: fontawesome/brands/js
      level: 2
    React Quickstart:
      icon: fontawesome/brands/react
    Angular Quickstart:
      icon: fontawesome/brands/angular
    Javascript Quickstart:
      icon: fontawesome/brands/js
    Next.js Quickstart:
      icon: assets/libs/custom-icons/nextjs.svg
    Spring Boot Quickstart:
      icon: assets/libs/custom-icons/spring-boot.svg
    Frontend Security:
      icon: fontawesome/solid/user-shield

  integrations:
    - name: Auth React SDK
      icon: assets/img/logo/react-logo.svg
      description: An SDK to integrate {{ product_name }} into React applications
      documentation_link: get-started/try-your-own-app/react/
      download_link: https://github.com/asgardeo/asgardeo-auth-react-sdk/releases/latest/download/asgardeo-react-app.zip
      source_link: https://github.com/asgardeo/asgardeo-auth-react-sdk
    - name: Auth SPA SDK
      icon: assets/img/logo/javascript-logo.svg
      description: An SDK to integrate {{ product_name }} into single page applications
      documentation_link: get-started/try-your-own-app/javascript/
      download_link: https://github.com/asgardeo/asgardeo-auth-spa-sdk/releases/latest/download/asgardeo-html-js-app.zip
      source_link: https://github.com/asgardeo/asgardeo-auth-spa-sdk
    - name: Angular OAuth2 OIDC
      icon: assets/img/logo/angular-logo.svg
      description: A library for implementing OAuth2 and OIDC in Angular applications
      source_link: https://github.com/manfredsteyer/angular-oauth2-oidc
    - name: Next Auth
      icon: assets/img/logo/nextjs-logo.svg
      dark_icon: assets/img/logo/nextjs-logo-dark.svg
      description: A library for implementing OAuth2 and OIDC in NextJS applications
      source_link: https://github.com/nextauthjs/next-auth
    - name: Auth Node SDK
      icon: assets/img/logo/expressjs-logo.svg
      dark_icon: assets/img/logo/expressjs-logo-dark.svg
      description: An SDK to integrate {{ product_name }} into JS/TS-based frameworks such as ExpressJS
      source_link: https://github.com/asgardeo/asgardeo-auth-node-sdk
    - name: Tomcat OIDC Agent
      icon: assets/img/logo/java-logo.svg
      description: A Tomcat agent for implementing login/logout for Tomcat web apps
      documentation_link: get-started/try-your-own-app/java-ee-oidc/
      download_link: https://github.com/asgardeo/asgardeo-tomcat-oidc-agent/releases/latest/download/oidc-sample-app.war
      source_link: https://github.com/asgardeo/asgardeo-tomcat-oidc-agent
    - name: Tomcat SAML Agent
      icon: assets/img/logo/java-logo.svg
      description: A SAML Tomcat agent for implementing SAML login/logout for Tomcat web apps
      documentation_link: get-started/try-your-own-app/java-ee-saml/
      download_link: https://github.com/asgardeo/asgardeo-tomcat-saml-agent/releases/latest/download/sample-app.war
      source_link: https://github.com/asgardeo/asgardeo-tomcat-saml-agent
    - name: Flutter AppAuth
      icon: assets/img/logo/flutter-logo.svg
      description: A wrapper for native AppAuth SDKs to integrate OAuth2 and OIDC providers into Flutter apps
      source_link: https://github.com/MaikuB/flutter_appauth/tree/master/flutter_appauth
    - name: React Native AppAuth
      icon: assets/img/logo/react-logo.svg
      description: An SDK to integrate OAuth2 and OIDC providers into React Native apps
      source_link: https://github.com/FormidableLabs/react-native-app-auth
    - name: AppAuth Android
      icon: assets/img/logo/android-logo.svg
      description: A client SDK to integrate OAuth2 and OIDC providers into Android applications
      source_link: https://github.com/openid/AppAuth-Android
    - name: AppAuth iOS
      icon: assets/img/logo/apple-idp-illustration.svg
      dark_icon: assets/img/logo/apple-logo-dark.svg
      description: A client SDK to integrate OAuth2 and OIDC providers into iOS applications
      source_link: https://github.com/openid/AppAuth-iOS
    - name: Android Mobile UI SDK
      icon: assets/img/logo/android-logo.svg
      description: A client SDK to integrate {{ product_name }} into Android mobile applications using "app-native authentication"
      documentation_link: https://asgardeo.github.io/mobile-ui-sdks/android/introduction.html
      source_link: https://github.com/asgardeo/mobile-ui-sdks/tree/main/android
  redoc_theme: '{
    "colors": {
      "primary": { "main": "#ff7300" }
    }
  }'
