swagger: '2.0'
info:
  description: This is the RESTful API for managing OAuth2 Authorized Apps
  version: "1.0.0"
  title: WSO2 Identity Server - OAuth2 Authorized Apps API
  contact:
    name: "WSO2 Identity Server"
    url: "https://wso2.com/identity-and-access-management/"
    email: "architecture@wso2.com"
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

schemes:
 - https
# host: is.wso2.com
# basePath: /t/{tenant-domain}/api/identity/1.0.0/

# tags are used for organizing operations
tags:
- name: developers
  description: Operations available to regular developers
security:
  - OAuth2: []
  - BasicAuth: []

paths:
  /{user-id}/authorized-apps:
    get:
      tags:
        - developers
      summary: list authorized applications of a user
      operationId: listUserAuthorizedApps
      description: |
        List approved OAuth applications for a given user
      parameters:
        - $ref: '#/parameters/usernamePathParams'
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/AuthorizedApp'
        401:
          $ref: '#/responses/Unauthorized'
        403:
          $ref: '#/responses/Forbidden'
        500:
          $ref: '#/responses/ServerError'
    delete:
      tags:
        - developers
      summary: "remove all authorized applications of a user"
      operationId:  deleteUserAuthorizedApps
      description: |
        Removes authorization from all OAuth apps of a given user
      parameters:
        - $ref: '#/parameters/usernamePathParams'
      responses:
        204:
          $ref: '#/responses/Deleted'
        401:
          $ref: '#/responses/Unauthorized'
        403:
          $ref: '#/responses/Forbidden'
        500:
          $ref: '#/responses/ServerError'
  /{user-id}/authorized-apps/{application-id}:
    get:
      tags:
        - developers
      summary: "retrieve autherized app by app ID for a user"
      operationId: listUserAuthorizedAppsByAppId
      description: |
        Retrived autherized OAuth apps by an app ID for a given user
      parameters:
        - $ref: '#/parameters/usernamePathParams'
        - $ref: '#/parameters/applicationNamePathParam'
      responses:
        200:
          description: search results matching criteria
          schema:
            $ref: '#/definitions/AuthorizedApp'
        401:
          $ref: '#/responses/Unauthorized'
        403:
          $ref: '#/responses/Forbidden'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/ServerError'
    delete:
      tags:
        - developers
      summary: "removes challenge question answers"
      operationId: deleteUserAuthorizedAppsByAppId
      description: |
        Removes autherized OAuth apps by an app ID for a given user
      parameters:
        - $ref: '#/parameters/usernamePathParams'
        - $ref: '#/parameters/applicationNamePathParam'
      responses:
        204:
          $ref: '#/responses/Deleted'
        401:
          $ref: '#/responses/Unauthorized'
        403:
          $ref: '#/responses/Forbidden'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/ServerError'
  /me/authorized-apps:
    get:
      tags:
        - developers
      summary: "list authorized applications for the authenticated user"
      operationId: listLoggedInUserAuthorizedApps
      description: |
        List approved OAuth applications of the authenticated user
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/AuthorizedApp'
        401:
          $ref: '#/responses/Unauthorized'
        403:
          $ref: '#/responses/Forbidden'
        500:
          $ref: '#/responses/ServerError'
    delete:
      tags:
        - developers
      summary: "removes authorized applications for the authenticated user"
      operationId: deleteLoggedInUserAuthorizedApps
      description: |
        Removes approved OAuth applications of the authenticated user
      responses:
        204:
          $ref: '#/responses/Deleted'
        401:
          $ref: '#/responses/Unauthorized'
        403:
          $ref: '#/responses/Forbidden'
        500:
          $ref: '#/responses/ServerError'
  /me/authorized-apps/{application-id}:
    get:
      tags:
        - developers
      summary: "retrieve authorized app by app ID for the authenticated user"
      operationId: getLoggedInUserAuthorizedAppByAppId
      description: |
        Retrived autherized OAuth app by an app ID for for the authenticated user
      parameters:
        - $ref: '#/parameters/applicationNamePathParam'
      responses:
        200:
          description: search results matching criteria
          schema:
            $ref: '#/definitions/AuthorizedApp'
        401:
          $ref: '#/responses/Unauthorized'
        403:
          $ref: '#/responses/Forbidden'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/ServerError'
    delete:
      tags:
        - developers
      summary: "removes authorized app by app ID for the authenticated user"
      operationId: deleteLoggedInUserAuthorizedAppByAppId
      description: |
        Removes autherized OAuth app by an app ID for for the authenticated user
      parameters:
        - $ref: '#/parameters/applicationNamePathParam'
      responses:
        204:
          $ref: '#/responses/Deleted'
        401:
          $ref: '#/responses/Unauthorized'
        403:
          $ref: '#/responses/Forbidden'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/ServerError'
parameters:
    usernamePathParams:
      in: path
      name: user-id
      required: true
      type: string
      description: username of the user
    applicationNamePathParam:
      in: path
      name: application-id
      required: true
      type: string
      description: Application ID

definitions:
  #-----------------------------------------------------
  # AuthorizedApp Properties object
  #-----------------------------------------------------
  AuthorizedApp:
    type: object
    required:
      - appId
      - clientId
    properties:
      appId:
        type: string
        example: FooApp
      clientId:
        type: string
        example: 7y7zPj4wDX3nRtfPKrmt8Auke44a

  #-----------------------------------------------------
  # The Error Response  object
  #-----------------------------------------------------
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: string
        example: "some_error_code"
      message:
        type: string
        example: "Some Error Message"
      description:
        type: string
        example: "Some Error Description"
      traceId:
        type: string
        example: "Some Correlation for Error Instance"
securityDefinitions:
  BasicAuth:
    type: basic
  # ClientCertificate:
  #   type: custom
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://localhost:9443/oauth/authorize
    tokenUrl: https://localhost:9443/oauth/token
    scopes:
      read: Grants read access
      write: Grants write access
      admin: Grants read and write access to administrative information
#-----------------------------------------------------
# Descriptions of common responses
#-----------------------------------------------------
responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: '#/definitions/Error'
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/Error'
  ServerError:
    description: Internal Server Error
    schema:
      $ref: '#/definitions/Error'
  InvalidInput:
    description: Invalid input, request invalid
    schema:
      $ref: '#/definitions/Error'
  Conflict:
    description: Element Already Exists
    schema:
      $ref: '#/definitions/Error'
  Created:
    description: Item Created
  OK:
    description: OK
  Deleted:
    description: Item Deleted
  Forbidden:
    description: Resource Forbidden

host: localhost:9443
basePath: /t/carbon.super/api/users/v1
