openapi: 3.0.1
info:
  title: Asgardeo - OAuth2 Dynamic Client Registration API
  description: |
    This document specifies an OAuth2 Dynamic Client Registration endpoint for Asgardeo.
  version: 1.1.0
servers:
- url: https:/api.asgardeo.io/t/{org-name}/api/identity/oauth2/dcr/v1.1
security:
- OAuth2: []
paths:
  /register:
    get:
      tags:
      - OAuth2 DCR
      summary: |
        Get application by name
      description: |
        "This API is used to get/retrieve an OAuth2 application by `client_name`. \n\n"
        <b>Scope(Permission) required:</b> `internal_dcr_view`
      operationId: getApplicationByName
      parameters:
      - name: client_name
        in: query
        description: The name of the OAuth2 client application.
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successfully Retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/application'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X 'GET' \
            'https://api.asgardeo.io/t/{organization-name}/api/identity/oauth2/dcr/v1.1/register?client_name={client-app-name}' \
            -H 'accept: application/json' \
            -H 'Authorization: Bearer {bearer_token}'                
    post:
      tags:
      - OAuth2 DCR
      summary: |
        Register an OAuth2 app
      description: "This API is used to create an OAuth2 application. 
        \n If your want to create your application to use the `implicit` or `authorization_code` grant types, you need to provide the `redirect_uri` field in your request.\
        \n If you are using any other grant type, \nsuch as `password`, you don't need to send the `redirect_uri` field in the request.
        \n Check the sample request given below.\n\n<b>Scope(Permission) required:</b> `internal_dcr_create`"
      operationId: registerApplication
      requestBody:
        description: Application information to register.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registrationRequest'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/application'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        409:
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X 'POST' \
            'https://api.asgardeo.io/t/{organization-name}/api/identity/oauth2/dcr/v1.1/register' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer {bearer_token}' \
            -d '{
            "redirect_uris": [
              "string"
            ],
            "client_name": "string",
            "client_id": "string",
            "client_secret": "string",
            "grant_types": [
              "authorization_code",
              "password"
            ],
            "jwks_uri": "string",
            "url": "string",
            "ext_param_client_id": "string",
            "ext_param_client_secret": "string",
            "contacts": [
              "string"
            ],
            "post_logout_redirect_uris": [
              "string"
            ],
            "request_uris": [
              "string"
            ],
            "ext_param_sp_template": "string",
            "backchannel_logout_uri": "string",
            "backchannel_logout_session_required": true
            }'
      x-codegen-request-body-name: registrationRequest
  /register/{client_id}:
    get:
      tags:
      - OAuth2 DCR
      summary: |
        Get application by ID  
      description: |
        "This API is used to retrieve an OAuth2 application by `client_id`. \n\n"
        <b>Scope(Permission) required:</b> `internal_dcr_view`
      operationId: getApplication
      parameters:
      - name: client_id
        in: path
        description: Unique identifier of the OAuth2 client application.
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successfully Retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/application'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X 'GET' \
            'https://api.asgardeo.io/t/{organization-name}/api/identity/oauth2/dcr/v1.1/register/{client-id}' \
            -H 'accept: application/json' \
            -H 'Authorization: Bearer {bearer_token}'                
    put:
      tags:
      - OAuth2 DCR
      summary: |
        Update an OAuth2 app
      description: |
        "This API is used to update an OAuth2 application.\n\n"
        <b>Scope(Permission) required:</b> `internal_dcr_update`
      operationId: updateApplication
      parameters:
      - name: client_id
        in: path
        description: Unique identifier for the OAuth2 client application.
        required: true
        schema:
          type: string
      requestBody:
        description: Application information to update.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        required: true
      responses:
        200:
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/application'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        409:
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X 'PUT' \
            'https://api.asgardeo.io/t/{organization-name}/api/identity/oauth2/dcr/v1.1/register/{client_id}' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer {bearer_token}' \
            -d '{
            "redirect_uris": [
              "string"
            ],
            "client_name": "client_application",
            "client_id": "string",
            "client_secret": "string",
            "grant_types": [
              "authorization_code",
              "password"
            ],
            "backchannel_logout_uri": "string",
            "backchannel_logout_session_required": true
            }'                
      x-codegen-request-body-name: updateRequest
    delete:
      tags:
      - OAuth2 DCR
      summary: |
        Delete an OAuth2 app
      description: |
        "This API is used to delete an OAuth2 application by `client_id`.\n\n"
        <b>Scope(Permission) required:</b> `internal_dcr_delete`
      operationId: deleteApplication
      parameters:
      - name: client_id
        in: path
        description: Unique identifier of the OAuth2 client application.
        required: true
        schema:
          type: string
      responses:
        204:
          description: Successfully deleted
          content: {}
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X 'DELETE' \
            'https://api.asgardeo.io/t/{organization-name}/api/identity/oauth2/dcr/v1.1/register/{client_id}' \
            -H 'accept: */*' \
            -H 'Authorization: Bearer {bearer_token}'                
      x-wso2-request: |
        curl -X DELETE -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{}' "https://api.asgardeo.io/t/{org-name}/api/identity/oauth2/dcr/v1.1/register/s6BhdRkqt3"
      x-wso2-response: |
        "HTTP/1.1 204 No Content"
components:
  schemas:
    registrationRequest:
      required:
      - client_name
      - redirect_uris
      type: object
      properties:
        redirect_uris:
          type: array
          items:
            type: string
          description: The redirect URI determines where Asgardeo will redirect users after authentication and logout.
        client_name:
          type: string
          description: The name of the OAuth2 client application.
        ext_param_client_id:
          type: string
          description: The public identifier of the application.
        ext_param_client_secret:
          type: string
          description: The secret corresponding to the `clientId` of the application. This is confidential and will be used to make requests and authenticate into your application.
        grant_types:
          type: array
          example:
            - authorization_code
            - password
          items:
            type: string
          description: "The This will determine how the application communicates with the token service. Asgardeo supports following grant types:
          <ul>
            <li>authorization_code</li>
            <li>client_credentials</li>
            <li>refresh_token</li>
            <li>implicit</li>
            <li>password</li>
          </ul>"
        jwks_uri:
          type: string
        url:
          type: string
        contacts:
          type: array
          items:
            type: string
        post_logout_redirect_uris:
          type: array
          items:
            type: string
        request_uris:
          type: array
          items:
            type: string
        ext_param_sp_template:
          type: string
        backchannel_logout_uri:
          type: string
          description: Represents the URL that is used for sending logout requests from the identity provider (IdP) to the application in a back-channel manner, without involving the user's browser.
        backchannel_logout_session_required:
          type: boolean
    updateRequest:
      type: object
      properties:
        redirect_uris:
          type: array
          items:
            type: string
        client_name:
          type: string
          example: "client_application"
          description: The name of the OAuth2 client application.
        client_id:
          type: string
          description: The public identifier of the application.
        client_secret:
          type: string
          description: The secret corresponding to the `clientId` of the application. This is confidential and will be used to make requests and authenticate into your application.
        grant_types:
          type: array
          example:
            - authorization_code
            - password
          items:
            type: string
          description: "The This will determine how the application communicates with the token service. Asgardeo supports following grant types:
          <ul>
            <li>authorization_code</li>
            <li>client_credentials</li>
            <li>refresh_token</li>
            <li>implicit</li>
            <li>password</li>
          </ul>"
        backchannel_logout_uri:
          type: string
        backchannel_logout_session_required:
          type: boolean
    application:
      type: object
      properties:
        client_id:
          type: string
          example: "s6BhdRkqt3"
          description: The public identifier of the application.
        client_secret:
          type: string
          example: "ZJYCqe3GGRvdrudKyZS0XhGv_Z45DuKhCUk0gBR1vZk"
          description: The secret corresponding to the `clientId` of the application. This is confidential and will be used to make requests and authenticate into your application.
        client_secret_expires_at:
          type: string
          example: "1577858400"
          description: The remaining time for expiry of the `client_secret`.
        redirect_uris:
          type: array
          items:
            type: string
        grant_types:
          type: array
          example:
            - authorization_code
            - password
          items:
            type: string
          description: "The This will determine how the application communicates with the token service. Asgardeo supports following grant types:
          <ul>
            <li>authorization_code</li>
            <li>client_credentials</li>
            <li>refresh_token</li>
            <li>implicit</li>
            <li>password</li>
          </ul>"
        client_name:
          type: string
          example: "client_application"
          description: The name of the OAuth2 client application.
    error:
      type: object
      properties:
        error:
          type: string
        error_description:
          type: string
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://api.asgardeo.io/t/{org-name}/oauth2/authorize
          tokenUrl: https://api.asgardeo.io/t/{org-name}/oauth2/token
          scopes: {}