openapi: 3.0.0
info:
  description: This is the RESTful API for handling user functionality manangement in WSO2 Identity Server.
  version: "1.0.0"
  title: WSO2 Identity Server - User Functionality Management API
  contact:
    name: "WSO2 Identity Server"
    url: "https://wso2.com/identity-and-access-management"
    email: "architecture@wso2.org"
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: user functionality management
    description: This REST API handles user functionality management. A functionality can be locked or unlocked for particular users via this API. 

security:
  - OAuth2: []
  - BasicAuth: []

paths:
  /me/user-functionality/{function-id}:
    get:
      tags:
        - user functionality management
      summary: |
        Get the lock status of a functionality for authenticated user
      description: |
        Get the status of a functionality for the authenticated user.

        <b>Permission required:</b> <br/>
          - none

        <b>Scope required:</b> <br/>
          - internal_login

      operationId: getLockStatusOfLoggedInUser
      parameters:
        - name: function-id
          in: path
          description: FunctionalityIdentifier.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LockStatusResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - user functionality management
      summary: Lock or Unlock a function for authenticated user
      operationId: changeStatusOfLoggedInUser
      description: |
        This API is used to lock or unlock a function for the authenticated user.

        <b>Permission required:</b> <br/>
          - none

        <b>Scope required:</b> <br/>
          - internal_login

      parameters:
        - name: function-id
          in: path
          description: FunctionalityIdentifier.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserStatusChangeRequest'
            examples:
              Lock:
                value:
                  action: LOCK
              UnLock:
                value:
                  action: UNLOCK
      responses:
        200:
          description: The function is successfully locked.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'

  '/{user-id}/user-functionality/{function-id}':
    get:
      tags:
        - user functionality management
      summary: |
        Get the lock status of a functionality for a user
      description: |
        Get the status of a functionality for a particular user.

        <b>Permission required:</b> <br/>
          - /permission/admin/manage/identity/identitymgt/view

        <b>Scope required:</b> <br/>
          - internal_identity_mgt_view

      operationId: getLockStatus
      parameters:
        - name: function-id
          in: path
          description: FunctionalityIdentifier.
          required: true
          schema:
            type: string
        - name: user-id
          in: path
          description: UserID.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LockStatusResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - user functionality management
      summary: Lock or Unlock a function for a user
      operationId: changeStatus
      description: |
        This API is used to lock or unlock a function for a particular user.

        <b>Permission required:</b> <br/>
          - /permission/admin/manage/identity/identitymgt/update

        <b>Scope required:</b> <br/>
          - internal_identity_mgt_update

      parameters:
        - name: function-id
          in: path
          description: FunctionalityIdentifier.
          required: true
          schema:
            type: string
        - name: user-id
          in: path
          description: UserID.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusChangeRequest'
            examples:
              Lock:
                value:
                  action: LOCK
                  timeToLock: 1594987178
                  functionalityLockReason: SecurityQuestionBasedBased
                  functionalityLockReasonCode: MaxFailedAttempts
              UnLock:
                value:
                  action: UNLOCK
      responses:
        200:
          description: The function is successfully locked.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    StatusChangeRequest:
      type: object
      required:
        - action
      properties:
        action:
          type: string
          enum: [ LOCK , UNLOCK]
          example: lock
          description: LOCK/UNLOCK
        timeToLock:
          type: string
          example: 1594987178
          description: Time in millisecond
        functionalityLockReason:
          type: string
          example: SecurityQuestionBasedBased
        functionalityLockReasonCode:
          type: string
    LockStatusResponse:
      type: object
      properties:
        lockStatus:
          type: boolean
          example: true
          description: returns true if it is locked
        unlockTime:
          type: string
          example: SecurityQuestionBasedBased
        lockReasonCode:
          type: string
        lockReason:
          type: string
          example: SecurityQuestionBasedBased
    UserStatusChangeRequest:
      type: object
      required:
        - action
      properties:
        action:
          type: string
          enum: [ LOCK , UNLOCK]
          example: lock
          description: LOCK/UNLOCK
        timeToLock:
          type: string
          example: 1594987178
          description: Time in millisecond

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: "AAA-00000"
        message:
          type: string
          example: "Some Error Message"
        description:
          type: string
          example: "Some Error Description"
        traceId:
          type: string
          example: "e0fbcfeb-3617-43c4-8dd0-7b7d38e13047"
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://localhost:9443/oauth2/authorize'
          tokenUrl: 'http://localhost:9763/oauth2/token'
          scopes: {}

servers:
  - url: 'https://{serverUrl}/t/{tenantDomain}/api/users/v1'
    variables:
      serverUrl:
        default: localhost:9443
      tenantDomain:
        default: carbon.super