openapi: 3.0.1
info:
  title: WSO2 Identity Server Scope Endpoint
  description: |
    The OAuth2 scope API in WSO2 Identity Server (IS) can be used to manage oauth2 scopes and scope bindings such as roles and permissions. Since OIDC scope is a sub category of OAuth2 scopes, these endpoints cannot have the same
    scope names as in WSO2 IS.
  contact:
    name: WSO2
    url: http://wso2.com/identity-and-access-management
    email: architecture@wso2.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://{serverUrl}/api/identity/oauth2/v1.0
  variables:
    serverUrl:
      default: localhost:9443
paths:
  /scopes:
    get:
      tags:
      - Scope Management
      summary: |
        Returns all available Scopes
      description: |
        This API is used to get all the available scopes.
      operationId: getScopes
      parameters:
      - name: startIndex
        in: query
        description: The start index of the list of scopes to be retrieved
        schema:
          type: integer
      - name: count
        in: query
        description: Number of scopes to retrieve from the point of the start index
        schema:
          type: integer
      - name: includeOIDCScopes
        in: query
        description: Retrieve OIDC scopes as well via OAuth2 scopes endpoint.
        schema:
          type: boolean
      - name: requestedScopes
        in: query
        description: If specified, requested set of scopes will be return.
        schema:
          type: string
      responses:
        200:
          description: Successfully Retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/scope'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-wso2-request: |
        curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" "https://localhost:9443/api/identity/oauth2/v1.0/scopes"
      x-wso2-response: |
        [{"name":"profile","description":"get all profile information","displayName":"profile","bindings":["role1","role2"]}]
    post:
      tags:
      - Scope Management
      summary: |
        Registers a Scope
      description: |
        This API is used to create a scope.
      operationId: registerScope
      requestBody:
        description: Define a scope with bindings to register it
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/scope'
        required: true
      responses:
        201:
          description: Successfully Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scope'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        409:
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-wso2-request: |
        curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{"name": "profile", "displayName": "profile", "description": "get all profile information", "bindings": ["role1", "role2"]}' "https://localhost:9443/api/identity/oauth2/v1.0/scopes"
      x-wso2-response: |
        "HTTP/1.1 201 Created"
        {"name":"profile","description":"get all profile information","displayName":"profile","bindings":["role1","role2"]}
      x-codegen-request-body-name: scope
  /scopes/name/{name}:
    get:
      tags:
      - Scope Management
      summary: |
        Returns a Scope by Scope Name
      description: |
        This API is used to retrieve details of a scope by a given scope name.
      operationId: getScope
      parameters:
      - name: name
        in: path
        description: Name of the scope that is to be retrieved
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successfully Retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scope'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-wso2-request: |
        curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" "https://localhost:9443/api/identity/oauth2/v1.0/scopes/name/profile"
      x-wso2-response: |
        {"name":"profile","description":"get all profile information","displayName":"profile","bindings":["role1","role2"]}
    put:
      tags:
      - Scope Management
      summary: |
        Updates a Scope
      description: |
        This API is used to update a scope by a given scope name.
      operationId: updateScope
      parameters:
      - name: name
        in: path
        description: Name of the scope that is to be updated
        required: true
        schema:
          type: string
      requestBody:
        description: updated scope
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/scopeToUpdate'
        required: true
      responses:
        200:
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scope'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-wso2-request: |
        curl -X PUT -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{"description": "get all profile information", "displayName": "profile", "bindings": ["role3", "role4"]}' "https://localhost:9443/api/identity/oauth2/v1.0/scopes/name/profile"
      x-wso2-response: |
        "HTTP/1.1 200 OK"
        {"name": "profile", "description": "get all profile information", "bindings": ["role3", "role4"]}
      x-codegen-request-body-name: scope
    delete:
      tags:
      - Scope Management
      summary: |
        Deletes a Scope
      description: |
        This API is used to delete a scope by a given scope name.
      operationId: deleteScope
      parameters:
      - name: name
        in: path
        description: Name of the scope that is to be deleted
        required: true
        schema:
          type: string
      responses:
        204:
          description: Successfully deleted
          content:
            application/json:
              schema:
                title: key
                type: string
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-wso2-request: |
        curl -X DELETE -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" "https://localhost:9443/api/identity/oauth2/v1.0/scopes/name/profile"
      x-wso2-response: |
        "HTTP/1.1 204 No Content"
    head:
      tags:
      - Scope Management
      summary: |
        Check Scope Existence using Scope Name
      description: |
        This API is used to check a scope's existence using a given scope name.
      operationId: isScopeExists
      parameters:
      - name: name
        in: path
        description: Name of the scope that is to be checked
        required: true
        schema:
          type: string
      responses:
        200:
          description: Scope Exists
          content:
            application/json:
              schema:
                title: key
                type: string
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-wso2-request: |
        curl -I -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" "https://localhost:9443/api/identity/oauth2/v1.0/scopes/name/profile"
      x-wso2-response: |
        "HTTP/1.1 200 OK"
components:
  schemas:
    scope:
      required:
      - displayName
      - name
      type: object
      properties:
        name:
          type: string
        displayName:
          type: string
        description:
          type: string
        bindings:
          type: array
          items:
            type: string
        scopeBindings:
          type: array
          items:
            $ref: '#/components/schemas/scopeBinding'
    scopeToUpdate:
      required:
      - displayName
      type: object
      properties:
        displayName:
          type: string
        description:
          type: string
        bindings:
          type: array
          items:
            type: string
        scopeBindings:
          type: array
          items:
            $ref: '#/components/schemas/scopeBinding'
    error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        description:
          type: string
    scopeBinding:
      type: object
      properties:
        bindingType:
          type: string
        binding:
          type: array
          items:
            type: string
