openapi: 3.0.1
info:
  title: WorkFlow Engine
  description: This is the RESTful API for managing WorkFlow Engines in WSO2 Identity
    Server
  contact:
    name: WSO2 Identity Server
    url: https://wso2.com/identity-and-access-management/
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
servers:
- url: https://{serverUrl}/t/{tenantDomain}/api/server/v1
  variables:
    servrUrl:
      default: localhost:9443
    tenantDomain:
      default: carbon.super
security:
- OAuth2: []
- BasicAuth: []
tags:
- name: default
  description: Secured Admin-only calls
paths:
  /workflow-engines:
    get:
      summary: Retrieve all the available workflow engines.
      description: |
        Retrieve metadata information of all the workflow engines in the system.

          <b>Permission required:</b>
            * /permission/admin/manage/humantask/viewtasks
      operationId: searchWorkFlowEngines
      responses:
        200:
          description: search results matching criteria
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkFlowEngine'
        401:
          description: Unauthorized
          content: {}
        403:
          description: Resource Forbidden
          content: {}
        404:
          description: The specified resource is not found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    WorkFlowEngine:
      required:
      - profileName
      type: object
      properties:
        profileName:
          type: string
          description: A unique name for the workflow engine.
          example: embeded_bps
        workerHostURL:
          type: string
          description: URL of the workflow worker node.
          example: https://localhost:9443/services
        managerHostURL:
          type: string
          description: URL of the workflow manager node.
          example: https://localhost:9443/services
        userName:
          type: string
          description: Username of the creator of the workflow engine.
          example: challengeQuestion1
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
          example: some_error_code
        message:
          type: string
          example: Some Error Message
        description:
          type: string
          example: Some Error Description
        traceId:
          type: string
          example: Some Trace ID
  responses:
    Created:
      description: Item Created
      content: {}
    Forbidden:
      description: Resource Forbidden
      content: {}
    NotFound:
      description: The specified resource is not found
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
    OK:
      description: OK
      content: {}
    ServerError:
      description: Internal Server Error
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content: {}
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://localhost:9443/oauth2/authorize
          tokenUrl: https://localhost:9443/oauth2/token
          scopes: {}
